// Copyright 2026 Andre Cipriani Bandarra
// SPDX-License-Identifier: Apache-2.0

//! Response and streaming chunk types for the DeepSeek API.

use serde::{Deserialize, Serialize};

use super::{
    chat::Role,
    tools::{ChunkToolCall, ToolCall},
};

/// Non-streaming chat completion response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ChatCompletionResponse {
    /// Unique identifier for the chat completion.
    pub id: String,

    /// Object type, always `"chat.completion"`.
    pub object: String,

    /// Unix timestamp of when the completion was created.
    pub created: u64,

    /// Model used for completion.
    pub model: String,

    /// List of completion choices generated by the model.
    pub choices: Vec<Choice>,

    /// Token usage metrics for the completion.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

impl ChatCompletionResponse {
    /// Helper to get the first choice's message text content.
    pub fn text(&self) -> Option<&str> {
        self.choices.first()?.message.content.as_deref()
    }

    /// Helper to get the first choice's reasoning content (DeepSeek-R1).
    pub fn reasoning_content(&self) -> Option<&str> {
        self.choices.first()?.message.reasoning_content.as_deref()
    }

    /// Helper to get the first choice's tool calls, if any.
    pub fn tool_calls(&self) -> Option<&[ToolCall]> {
        self.choices.first()?.message.tool_calls.as_deref()
    }
}

/// A single choice in a chat completion response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Choice {
    /// Choice index.
    pub index: usize,

    /// Assistant response message.
    pub message: ResponseMessage,

    /// Reason why the model stopped generating tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// Message returned by the model.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct ResponseMessage {
    /// Role of the response (typically `Assistant`).
    pub role: Role,

    /// Text response content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Reasoning trace for DeepSeek-R1 (`deepseek-reasoner`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,

    /// Tool calls invoked by the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
}

/// Breakdown of prompt tokens including cache hits.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct PromptTokensDetails {
    /// Number of tokens read from the prompt cache.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<u32>,
}

/// Token usage statistics returned by DeepSeek.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct Usage {
    /// Number of tokens in the prompt.
    pub prompt_tokens: u32,

    /// Number of tokens in the generated completion.
    pub completion_tokens: u32,

    /// Total number of tokens used.
    pub total_tokens: u32,

    /// DeepSeek prompt cache hit tokens (read from cache).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_cache_hit_tokens: Option<u32>,

    /// DeepSeek prompt cache miss tokens (processed into cache).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_cache_miss_tokens: Option<u32>,

    /// Detailed breakdown of prompt tokens.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<PromptTokensDetails>,
}

/// A single chunk in an SSE streaming chat completion response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ChatCompletionChunk {
    /// Unique identifier for the chunk.
    pub id: String,

    /// Object type, always `"chat.completion.chunk"`.
    pub object: String,

    /// Unix timestamp of creation.
    pub created: u64,

    /// Model used.
    pub model: String,

    /// Completion choice deltas.
    pub choices: Vec<ChunkChoice>,

    /// Token usage metrics (usually present on the final chunk if requested).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub usage: Option<Usage>,
}

/// Choice delta in a streaming response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ChunkChoice {
    /// Choice index.
    pub index: usize,

    /// Incremental content delta.
    pub delta: ChunkDelta,

    /// Finish reason when generation completes.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
}

/// Incremental delta received in an SSE stream chunk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct ChunkDelta {
    /// Role delta (usually present only in the first chunk).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,

    /// Incremental text content.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Incremental reasoning content delta (DeepSeek-R1).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning_content: Option<String>,

    /// Incremental tool call deltas.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ChunkToolCall>>,
}
