// Copyright 2026 Andre Cipriani Bandarra
// SPDX-License-Identifier: Apache-2.0

//! Tool and function calling types for DeepSeek.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Tool definition passed to the model.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Tool {
    /// The type of tool (currently only `"function"` is supported).
    #[serde(rename = "type")]
    pub tool_type: ToolType,

    /// The function specification.
    pub function: FunctionDefinition,
}

impl Tool {
    /// Creates a new function tool.
    pub fn function(name: impl Into<String>, description: Option<String>, parameters: Option<Value>) -> Self {
        Self {
            tool_type: ToolType::Function,
            function: FunctionDefinition {
                name: name.into(),
                description,
                parameters,
            },
        }
    }
}

/// Type of tool.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolType {
    /// Function tool.
    Function,
}

/// Specification of a callable function tool.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionDefinition {
    /// Name of the function.
    pub name: String,

    /// Description of the function purpose and behavior.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// JSON schema for the function arguments.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Value>,
}

/// Controls how the model calls tools.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ToolChoice {
    /// Predefined choice mode (`"none"`, `"auto"`, or `"required"`).
    Mode(ToolChoiceMode),
    /// Force a specific named function.
    Function(NamedToolChoice),
}

/// Mode for tool selection.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ToolChoiceMode {
    /// Do not call any tool.
    None,
    /// Automatically decide whether to call tools.
    Auto,
    /// Must call at least one tool.
    Required,
}

/// Forcing a specific function call.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NamedToolChoice {
    #[serde(rename = "type")]
    pub tool_type: ToolType,
    pub function: NamedToolChoiceFunction,
}

impl NamedToolChoice {
    /// Creates a named tool choice forcing a specific function.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            tool_type: ToolType::Function,
            function: NamedToolChoiceFunction { name: name.into() },
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct NamedToolChoiceFunction {
    pub name: String,
}

/// Tool call generated by the model in a response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolCall {
    /// Provider-assigned unique ID of the tool call.
    pub id: String,

    /// Tool type (`"function"`).
    #[serde(rename = "type")]
    pub tool_type: ToolType,

    /// Function call details.
    pub function: FunctionCall,
}

/// Function invocation arguments generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct FunctionCall {
    /// Name of the function to call.
    pub name: String,

    /// JSON string of the arguments.
    pub arguments: String,
}

/// Tool call delta within a streaming response chunk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct ChunkToolCall {
    /// The index of the tool call in the array.
    pub index: usize,

    /// Tool call ID (usually provided in the first chunk for this index).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Tool type (e.g. `"function"`).
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub tool_type: Option<ToolType>,

    /// Function chunk delta.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function: Option<ChunkFunctionCall>,
}

/// Function call chunk within a streaming delta.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct ChunkFunctionCall {
    /// Incremental function name (or full name in first chunk).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Incremental arguments JSON fragment.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}
